name: Build LaTeX document

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: report/main.tex

      - name: Rename PDF
        run: mv main.pdf report.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v6
        with:
          name: PDF
          path: report.pdf

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v6

      - name: Download PDF
        uses: actions/download-artifact@v7
        with:
          name: PDF

      - name: Create release
        uses: Roang-zero1/github-create-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload PDF to release
        uses: Roang-zero1/github-upload-release-artifacts-action@v3
        with:
          args: "report.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}